# Generated by Django 4.0.2 on 2022-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kefir_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
